### PR TITLE
Use of `typeof` instead of `||`

### PR DESCRIPTION
**Pull request by ghost**
By using `||` it evaluates `window`; with this change, it checks for its existence.

### CODE REVIEW

**Comment by GreenGremlin** [comment]
Can you explain what the downside of evaluating an undefined value is?

**Comment by ghost** [comment]
I'm doing some shallow testing and by importing your module, it evaluates
`window`, which doesn't exists, so it breaks the test; that's why I think
it's safer to check for its existence rather than evaluating it.

-- 
Omar Gómez Figueroa

El día 22 de febrero de 2017 a las 1:23:49 p.m., Jonathan (
notifications@github.com) escrito:

**Comment by ghost** [comment]
I think we can avoid the evaluation altogether when in `node`:
```JavaScript
var scrollElem;

function detectScrollElem() {
  // Defaults to zero if `pageYOffset` doesn’t exists.
  var startScrollTop = window.hasOwnProperty('pageYOffset') ? window.pageYOffset : 0;
  document.documentElement.scrollTop = startScrollTop + 1;
  // In the case of IE < 9, `window.pageYOffset` will be `undefined`
  // so it won’t return `document.body`.
  if (window.pageYOffset === startScrollTop) return document.body;  // Chrome (non-standard)
  document.documentElement.scrollTop = startScrollTop;

  return document.documentElement; // IE & FF (standard)
}

module.exports = function scrollDoc() {
  return scrollElem || (scrollElem = detectScrollElem());
}

```

**Comment by iamdey** [comment]
agree, 
this library fails to load in a node environment. In my case the app is also SSR.
I can make an ugly condition, but I won't:

```js
// normal es6 import
import otherThingUniversal from 'other-thing';

let scrollDoc = () => ({});
// I declared the constant in webpack config
if (BUILD_TARGET === 'browser') {
   scrollDoc = require('scroll-doc');
}
```

**Pull request merged**
